# Generated by Django 2.2.16 on 2022-10-25 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sa', '0002_member_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEventNotify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_email', models.EmailField(blank=True, max_length=512, null=True)),
                ('user', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserGpsEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('device_timestamp', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='Member',
            new_name='Profile',
        ),
        migrations.RemoveField(
            model_name='membermonitor',
            name='member',
        ),
        migrations.RemoveField(
            model_name='membersession',
            name='member',
        ),
        migrations.RemoveField(
            model_name='tagentry',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='tagentry',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='gpsc',
            name='member',
        ),
        migrations.RemoveField(
            model_name='mymed',
            name='member',
        ),
        migrations.RemoveField(
            model_name='token',
            name='member',
        ),
        migrations.RemoveField(
            model_name='videocu',
            name='member',
        ),
        migrations.AddField(
            model_name='mymed',
            name='user',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='token',
            name='user',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='MemberGpsEntry',
        ),
        migrations.DeleteModel(
            name='MemberMonitor',
        ),
        migrations.DeleteModel(
            name='MemberSession',
        ),
        migrations.DeleteModel(
            name='TagEntry',
        ),
    ]
